targets:
    $default:
        builders:
            freezed:
                generate_for:
                    include:
                        - lib/app/data/models/**/*.dart
                        - lib/shared/network/apevolo_com/models/**/*.dart
                        - lib/features/**/*.dart
            json_serializable:
                options:
                    explicit_to_json: true
                    create_factory: true
                generate_for:
                    include:
                        - lib/app/data/models/**/*.dart
                        - lib/shared/network/apevolo_com/models/**/*.dart
                        - lib/shared/network/apevolo_com/models/*.dart
                        - lib/features/**/*.dart
            riverpod_generator:
                generate_for:
                    include:
                        - lib/features/**/*.dart
                        - lib/shared/**/*.dart
