name: apevolo_flutter
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
    sdk: '>=3.2.3 <4.0.0'

dependencies:
    cupertino_icons: ^1.0.2
    fluentui_system_icons: ^1.1.226
    uuid: ^3.0.6
    get: 4.6.6
    crypto: ^3.0.3
    pointycastle: ^3.7.4
    encrypt: ^5.0.3
    dio: ^5.8.0+1
    hive: ^2.2.3
    hive_flutter: ^1.1.0
    darq: 2.0.0
    flutter:
        sdk: flutter
    flutter_localization: ^0.2.0
    retrofit: '>=4.0.0 <5.0.0'
    logger: any #for logging purpose
    json_annotation: ^4.9.0
    freezed_annotation: ^3.0.0
    flutter_localizations:
        sdk: flutter
    flutter_svg: ^2.1.0

dev_dependencies:
    flutter_lints: ^2.0.0
    flutter_test:
        sdk: flutter
    retrofit_generator: ^9.1.9
    build_runner: ^2.4.15
    json_serializable: ^6.9.0
    freezed: ^3.0.6
    build_web_compilers: ^4.1.4

flutter:
    assets:
        - assets/certificate/
        - assets/image/
        - assets/svg/
    uses-material-design: true
